name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        ports:
          # Opens tcp port 6379 on the host and service container
          - 5432:5432  
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
       

    steps:
      # - uses: actions/checkout@v3
      - name: Test connect 
        run: ping -c 4 postgres
    # - name: Set up Elixir
    #   uses: erlef/setup-beam@988e02bfe678367a02564f65ca2e37726dc0268f
    #   with:
    #     elixir-version: '1.12.3' # Define the elixir version [required]
    #     otp-version: '24.1' # Define the OTP version [required]
    # - name: Restore dependencies cache
    #   uses: actions/cache@v3
    #   with:
    #     path: deps
    #     key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
    #     restore-keys: ${{ runner.os }}-mix-
    # - name: Install dependencies
    #   run: mix deps.get
    # - name: Run tests
    #   run: mix test
      # # Environment variables used by the `client.js` script to create a new PostgreSQL table.
      #   env:
      #     # The hostname used to communicate with the PostgreSQL service container
      #     POSTGRES_HOST: postgres
      #     # The default PostgreSQL port
      #     POSTGRES_PORT: 5432
